<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ASDP1556PO01976" name="com.Bing.Testing.Testing" tests="5" failures="0" timestamp="03 Jul 2018 11:09:20 GMT" time="4.744" errors="1">
  <testcase name="Step_05_Swap_Text" time="1.130" classname="com.Bing.Testing.Testing">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;&gt; but was:&lt;Hello&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<> but was:<Hello>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.Bing.Action.Action.Swap_Values(Action.java:58)
at com.Bing.Testing.Testing.Step_05_Swap_Text(Testing.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step_05_Swap_Text -->
  <testcase name="Step_02_Enter_Url" time="2.737" classname="com.Bing.Testing.Testing"/>
  <testcase name="Step_03_Selecting_Language" time="0.732" classname="com.Bing.Testing.Testing"/>
  <testcase name="Step_06_Clear_Text" time="0.082" classname="com.Bing.Testing.Testing"/>
  <testcase name="Step_04_Giving_Input" time="0.063" classname="com.Bing.Testing.Testing"/>
</testsuite> <!-- com.Bing.Testing.Testing -->
